DELETE FROM XCCCDESCRIPTION WHERE XCCCREF_UUID IN (SELECT UUID FROM XRSCALCPROFDATA);

DELETE FROM XCCCDESCRIPTION WHERE XCCCREF_UUID IN (SELECT UUID FROM XRSESTPROFDATA);

DELETE FROM XCCCDESCRIPTION WHERE XCCCREF_UUID IN (SELECT UUID FROM XRSCALIBRATIONSTRUCTDATA);

DELETE FROM XCCCDESCRIPTION WHERE XCCCREF_UUID IN (SELECT UUID FROM XRSMARKETFACTORSETDATA);

DELETE FROM XCCCDESCRIPTION WHERE XCCCREF_UUID IN (SELECT UUID FROM XRSYIELDCURVESETTINGSDATA);

DELETE FROM XCCCDESCRIPTION WHERE XCCCREF_UUID IN (SELECT UUID FROM XRSTIMESERIESSETTINGSDATA);

DELETE FROM XRSCALCPROFDATA_KEYFIGURE;

DELETE FROM XRSCALCPROFHIST;

DELETE FROM XRSCALCPROFDATA;

DELETE FROM XRSCALCPROF;

DELETE FROM XRSESTPROFHIST;

DELETE FROM XRSESTPROFDATA;

DELETE FROM XRSESTPROF;

DELETE FROM XRSCALIBRATIONCELL;

DELETE FROM XRSCALIBRATIONSTRUCTHIST;

DELETE FROM XRSCALIBRATIONSTRUCTDATA;

DELETE FROM XRSCALIBRATIONSTRUCT;

DELETE FROM XRSMARKETFACTORSETDATA_MF;

DELETE FROM XRSMARKETFACTORSETHIST;

DELETE FROM XRSMARKETFACTORSETDATA;

DELETE FROM XRSMARKETFACTORSET;

DELETE FROM XRSCALCMODELSETTINGS;

DELETE FROM XRSMONTECARLOSETTINGS;

DELETE FROM XRSSMITHWILSONSETTINGS;

DELETE FROM XRSYIELDCURVESETTINGSHIST;

DELETE FROM XRSYIELDCURVESETTINGSDATA;

DELETE FROM XRSYIELDCURVESETTINGS;

DELETE FROM XRSTIMESERIESSETTINGSHIST;

DELETE FROM XRSTIMESERIESSETTINGSDATA;

DELETE FROM XRSTIMESERIESSETTINGS;
